version: '3.9'

services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: franto
      MONGO_INITDB_ROOT_PASSWORD: adrien
      MONGO_INITDB_DATABASE: etudiant-service
    volumes:
      - ./data:/data/db
